# Generated by Django 3.1.7 on 2021-03-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchangeRateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('from_currency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('to_currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('to_currency_name', models.CharField(blank=True, max_length=50, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('last_refreshed', models.DateTimeField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=30, null=True)),
                ('bid_price', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('ask_price', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
            ],
        ),
    ]
